/* 
 * Rasa - Server Endpoints
 *
 * The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ApiClient.Client.OpenAPIDateConverter;

namespace ApiClient.Model
{
    /// <summary>
    /// Intent of the text
    /// </summary>
    [DataContract]
    public partial class Intent : IEquatable<Intent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Intent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Intent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Intent" /> class.
        /// </summary>
        /// <param name="confidence">Confidence of the intent (required).</param>
        /// <param name="name">Intent name (required).</param>
        public Intent(decimal confidence = default(decimal), string name = default(string))
        {
            // to ensure "confidence" is required (not null)
            if (confidence == null)
            {
                throw new InvalidDataException("confidence is a required property for Intent and cannot be null");
            }
            else
            {
                this.Confidence = confidence;
            }

            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for Intent and cannot be null");
            }
            else
            {
                this.Name = name;
            }

        }

        /// <summary>
        /// Confidence of the intent
        /// </summary>
        /// <value>Confidence of the intent</value>
        [DataMember(Name = "confidence", EmitDefaultValue = false)]
        public decimal Confidence { get; set; }

        /// <summary>
        /// Intent name
        /// </summary>
        /// <value>Intent name</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Intent {\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Intent);
        }

        /// <summary>
        /// Returns true if Intent instances are equal
        /// </summary>
        /// <param name="input">Instance of Intent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Intent input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Confidence == input.Confidence ||
                    this.Confidence.Equals(input.Confidence)
                ) &&
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Confidence.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        public static implicit operator Intent(ParseResult v)
        {
            throw new NotImplementedException();
        }
    }

}
