/* 
 * Rasa - Server Endpoints
 *
 * The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ApiClient.Client.OpenAPIDateConverter;

namespace ApiClient.Model
{
    /// <summary>
    /// Name of the active form
    /// </summary>
    [DataContract]
    public partial class TrackerActiveForm : IEquatable<TrackerActiveForm>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerActiveForm" /> class.
        /// </summary>
        /// <param name="name">Name of the acive form.</param>
        public TrackerActiveForm(string name = default(string))
        {
            this.Name = name;
        }

        /// <summary>
        /// Name of the acive form
        /// </summary>
        /// <value>Name of the acive form</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }


        [DataMember(Name = "validate", EmitDefaultValue = false)]
        public bool Validate { get; set; }
        [DataMember(Name = "rejected", EmitDefaultValue = false)]
        public bool Rejected { get; set; }
        [DataMember(Name = "trigger_message", EmitDefaultValue = false)]
        public ParseResult TriggerMessage { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrackerActiveForm {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TrackerActiveForm);
        }

        /// <summary>
        /// Returns true if TrackerActiveForm instances are equal
        /// </summary>
        /// <param name="input">Instance of TrackerActiveForm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackerActiveForm input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
