/* 
 * Rasa - Server Endpoints
 *
 * The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vevro.Rasa.ApiClient.Client.OpenAPIDateConverter;

namespace Vevro.Rasa.ApiClient.Model
{
    /// <summary>
    /// PredictResult
    /// </summary>
    [DataContract]
    public partial class PredictResult : IEquatable<PredictResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PredictResult" /> class.
        /// </summary>
        /// <param name="scores">Prediction results.</param>
        /// <param name="policy">Policy which predicted the most likely action.</param>
        /// <param name="tracker">tracker.</param>
        public PredictResult(List<PredictResultScores> scores = default(List<PredictResultScores>), string policy = default(string), Tracker tracker = default(Tracker))
        {
            this.Scores = scores;
            this.Policy = policy;
            this.Tracker = tracker;
        }

        /// <summary>
        /// Prediction results
        /// </summary>
        /// <value>Prediction results</value>
        [DataMember(Name = "scores", EmitDefaultValue = false)]
        public List<PredictResultScores> Scores { get; set; }

        /// <summary>
        /// Policy which predicted the most likely action
        /// </summary>
        /// <value>Policy which predicted the most likely action</value>
        [DataMember(Name = "policy", EmitDefaultValue = false)]
        public string Policy { get; set; }

        /// <summary>
        /// Gets or Sets Tracker
        /// </summary>
        [DataMember(Name = "tracker", EmitDefaultValue = false)]
        public Tracker Tracker { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PredictResult {\n");
            sb.Append("  Scores: ").Append(Scores).Append("\n");
            sb.Append("  Policy: ").Append(Policy).Append("\n");
            sb.Append("  Tracker: ").Append(Tracker).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PredictResult);
        }

        /// <summary>
        /// Returns true if PredictResult instances are equal
        /// </summary>
        /// <param name="input">Instance of PredictResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PredictResult input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Scores == input.Scores ||
                    this.Scores != null &&
                    input.Scores != null &&
                    this.Scores.SequenceEqual(input.Scores)
                ) &&
                (
                    this.Policy == input.Policy ||
                    (this.Policy != null &&
                    this.Policy.Equals(input.Policy))
                ) &&
                (
                    this.Tracker == input.Tracker ||
                    (this.Tracker != null &&
                    this.Tracker.Equals(input.Tracker))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Scores != null)
                    hashCode = hashCode * 59 + this.Scores.GetHashCode();
                if (this.Policy != null)
                    hashCode = hashCode * 59 + this.Policy.GetHashCode();
                if (this.Tracker != null)
                    hashCode = hashCode * 59 + this.Tracker.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
