/* 
 * Rasa - Server Endpoints
 *
 * The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using ApiClient.Client;
using ApiClient.Model;

namespace ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieve the loaded domain
        /// </summary>
        /// <remarks>
        /// Returns the domain specification the currently loaded model is using.
        /// </remarks>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Domain</returns>
        Domain DomainGet();

        /// <summary>
        /// Retrieve the loaded domain
        /// </summary>
        /// <remarks>
        /// Returns the domain specification the currently loaded model is using.
        /// </remarks>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Domain</returns>
        ApiResponse<Domain> DomainGetWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieve the loaded domain
        /// </summary>
        /// <remarks>
        /// Returns the domain specification the currently loaded model is using.
        /// </remarks>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Domain</returns>
        System.Threading.Tasks.Task<Domain> DomainGetAsync();

        /// <summary>
        /// Retrieve the loaded domain
        /// </summary>
        /// <remarks>
        /// Returns the domain specification the currently loaded model is using.
        /// </remarks>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Domain)</returns>
        System.Threading.Tasks.Task<ApiResponse<Domain>> DomainGetAsyncWithHttpInfo();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainApi : IDomainApiSync, IDomainApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DomainApi : IDomainApi
    {
        private ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainApi(String basePath)
        {
            this.Configuration = ApiClient.Client.Configuration.MergeConfigurations(
                ApiClient.Client.GlobalConfiguration.Instance,
                new ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DomainApi(ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ApiClient.Client.Configuration.MergeConfigurations(
                ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DomainApi(ApiClient.Client.ISynchronousClient client, ApiClient.Client.IAsynchronousClient asyncClient, ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieve the loaded domain Returns the domain specification the currently loaded model is using.
        /// </summary>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Domain</returns>
        public Domain DomainGet()
        {
            ApiClient.Client.ApiResponse<Domain> localVarResponse = DomainGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the loaded domain Returns the domain specification the currently loaded model is using.
        /// </summary>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Domain</returns>
        public ApiClient.Client.ApiResponse<Domain> DomainGetWithHttpInfo()
        {
            ApiClient.Client.RequestOptions requestOptions = new ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json",
                "application/yaml"
            };

            var localVarContentType = ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (JWT) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                requestOptions.HeaderParameters.Add("Authorization", "Basic " + ApiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (TokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                foreach (var kvp in ApiClient.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get<Domain>("/domain", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("DomainGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieve the loaded domain Returns the domain specification the currently loaded model is using.
        /// </summary>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Domain</returns>
        public async System.Threading.Tasks.Task<Domain> DomainGetAsync()
        {
            ApiClient.Client.ApiResponse<Domain> localVarResponse = await DomainGetAsyncWithHttpInfo();
            return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the loaded domain Returns the domain specification the currently loaded model is using.
        /// </summary>
        /// <exception cref="ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Domain)</returns>
        public async System.Threading.Tasks.Task<ApiClient.Client.ApiResponse<Domain>> DomainGetAsyncWithHttpInfo()
        {

            ApiClient.Client.RequestOptions requestOptions = new ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json",
                "application/yaml"
            };

            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);

            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);


            // authentication (JWT) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                requestOptions.HeaderParameters.Add("Authorization", "Basic " + ApiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (TokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                foreach (var kvp in ApiClient.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<Domain>("/domain", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("DomainGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
